<template>
    <section>
        <div id="tags">
            <ul>
                <li>
                    Kitesurf
                </li>
                <li>
                    Kitesurf
                </li>
                <li>
                    Kitesurf
                </li>
                <li>
                    Kitesurf
                </li>
                <li>
                    Kitesurf
                </li>
            </ul>
        </div>
    </section>
</template>
